// Code generated by MockGen. DO NOT EDIT.
// Source: /home/robi/ngoding/pribadi/example-db-transaction-golang/services/coba_svc/domain/repository/coba_satu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "coba/services/coba_svc/domain/entity"
	context "context"
	reflect "reflect"

	goutils "github.com/Muruyung/go-utilities"
	gomock "github.com/golang/mock/gomock"
)

// MockCobaSatuRepository is a mock of CobaSatuRepository interface.
type MockCobaSatuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCobaSatuRepositoryMockRecorder
}

// MockCobaSatuRepositoryMockRecorder is the mock recorder for MockCobaSatuRepository.
type MockCobaSatuRepositoryMockRecorder struct {
	mock *MockCobaSatuRepository
}

// NewMockCobaSatuRepository creates a new mock instance.
func NewMockCobaSatuRepository(ctrl *gomock.Controller) *MockCobaSatuRepository {
	mock := &MockCobaSatuRepository{ctrl: ctrl}
	mock.recorder = &MockCobaSatuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCobaSatuRepository) EXPECT() *MockCobaSatuRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCobaSatuRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCobaSatuRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCobaSatuRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockCobaSatuRepository) Get(ctx context.Context, query goutils.QueryBuilderInteractor) (*entity.CobaSatu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, query)
	ret0, _ := ret[0].(*entity.CobaSatu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCobaSatuRepositoryMockRecorder) Get(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCobaSatuRepository)(nil).Get), ctx, query)
}

// GetCount mocks base method.
func (m *MockCobaSatuRepository) GetCount(ctx context.Context, query goutils.QueryBuilderInteractor) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount", ctx, query)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCount indicates an expected call of GetCount.
func (mr *MockCobaSatuRepositoryMockRecorder) GetCount(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockCobaSatuRepository)(nil).GetCount), ctx, query)
}

// GetList mocks base method.
func (m *MockCobaSatuRepository) GetList(ctx context.Context, query goutils.QueryBuilderInteractor) ([]*entity.CobaSatu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, query)
	ret0, _ := ret[0].([]*entity.CobaSatu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockCobaSatuRepositoryMockRecorder) GetList(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockCobaSatuRepository)(nil).GetList), ctx, query)
}

// Save mocks base method.
func (m *MockCobaSatuRepository) Save(ctx context.Context, data *entity.CobaSatu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCobaSatuRepositoryMockRecorder) Save(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCobaSatuRepository)(nil).Save), ctx, data)
}

// Update mocks base method.
func (m *MockCobaSatuRepository) Update(ctx context.Context, id string, data *entity.CobaSatu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCobaSatuRepositoryMockRecorder) Update(ctx, id, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCobaSatuRepository)(nil).Update), ctx, id, data)
}
