// Code generated by MockGen. DO NOT EDIT.
// Source: /home/robi/ngoding/pribadi/coba-coba/services/coba_svc/domain/usecase/coba_satu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "coba/services/coba_svc/domain/entity"
	usecase "coba/services/coba_svc/domain/usecase"
	context "context"
	reflect "reflect"

	goutils "github.com/Muruyung/go-utilities"
	gomock "github.com/golang/mock/gomock"
)

// MockCobaSatuUseCase is a mock of CobaSatuUseCase interface.
type MockCobaSatuUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCobaSatuUseCaseMockRecorder
}

// MockCobaSatuUseCaseMockRecorder is the mock recorder for MockCobaSatuUseCase.
type MockCobaSatuUseCaseMockRecorder struct {
	mock *MockCobaSatuUseCase
}

// NewMockCobaSatuUseCase creates a new mock instance.
func NewMockCobaSatuUseCase(ctrl *gomock.Controller) *MockCobaSatuUseCase {
	mock := &MockCobaSatuUseCase{ctrl: ctrl}
	mock.recorder = &MockCobaSatuUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCobaSatuUseCase) EXPECT() *MockCobaSatuUseCaseMockRecorder {
	return m.recorder
}

// CreateCobaSatu mocks base method.
func (m *MockCobaSatuUseCase) CreateCobaSatu(ctx context.Context, dto usecase.DTOCobaSatu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCobaSatu", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCobaSatu indicates an expected call of CreateCobaSatu.
func (mr *MockCobaSatuUseCaseMockRecorder) CreateCobaSatu(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCobaSatu", reflect.TypeOf((*MockCobaSatuUseCase)(nil).CreateCobaSatu), ctx, dto)
}

// DeleteCobaSatu mocks base method.
func (m *MockCobaSatuUseCase) DeleteCobaSatu(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCobaSatu", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCobaSatu indicates an expected call of DeleteCobaSatu.
func (mr *MockCobaSatuUseCaseMockRecorder) DeleteCobaSatu(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCobaSatu", reflect.TypeOf((*MockCobaSatuUseCase)(nil).DeleteCobaSatu), ctx, id)
}

// GetCobaSatuByID mocks base method.
func (m *MockCobaSatuUseCase) GetCobaSatuByID(ctx context.Context, id string) (*entity.CobaSatu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCobaSatuByID", ctx, id)
	ret0, _ := ret[0].(*entity.CobaSatu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCobaSatuByID indicates an expected call of GetCobaSatuByID.
func (mr *MockCobaSatuUseCaseMockRecorder) GetCobaSatuByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCobaSatuByID", reflect.TypeOf((*MockCobaSatuUseCase)(nil).GetCobaSatuByID), ctx, id)
}

// GetListCobaSatu mocks base method.
func (m *MockCobaSatuUseCase) GetListCobaSatu(ctx context.Context, request *goutils.RequestOption) ([]*entity.CobaSatu, *goutils.MetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListCobaSatu", ctx, request)
	ret0, _ := ret[0].([]*entity.CobaSatu)
	ret1, _ := ret[1].(*goutils.MetaResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListCobaSatu indicates an expected call of GetListCobaSatu.
func (mr *MockCobaSatuUseCaseMockRecorder) GetListCobaSatu(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListCobaSatu", reflect.TypeOf((*MockCobaSatuUseCase)(nil).GetListCobaSatu), ctx, request)
}

// UpdateCobaSatu mocks base method.
func (m *MockCobaSatuUseCase) UpdateCobaSatu(ctx context.Context, id string, dto usecase.DTOCobaSatu) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCobaSatu", ctx, id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCobaSatu indicates an expected call of UpdateCobaSatu.
func (mr *MockCobaSatuUseCaseMockRecorder) UpdateCobaSatu(ctx, id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCobaSatu", reflect.TypeOf((*MockCobaSatuUseCase)(nil).UpdateCobaSatu), ctx, id, dto)
}
