// Code generated by MockGen. DO NOT EDIT.
// Source: /home/robi/ngoding/pribadi/coba-coba/services/coba_svc/domain/usecase/coba_dua.go

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "coba/services/coba_svc/domain/entity"
	usecase "coba/services/coba_svc/domain/usecase"
	context "context"
	reflect "reflect"

	goutils "github.com/Muruyung/go-utilities"
	gomock "github.com/golang/mock/gomock"
)

// MockCobaDuaUseCase is a mock of CobaDuaUseCase interface.
type MockCobaDuaUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCobaDuaUseCaseMockRecorder
}

// MockCobaDuaUseCaseMockRecorder is the mock recorder for MockCobaDuaUseCase.
type MockCobaDuaUseCaseMockRecorder struct {
	mock *MockCobaDuaUseCase
}

// NewMockCobaDuaUseCase creates a new mock instance.
func NewMockCobaDuaUseCase(ctrl *gomock.Controller) *MockCobaDuaUseCase {
	mock := &MockCobaDuaUseCase{ctrl: ctrl}
	mock.recorder = &MockCobaDuaUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCobaDuaUseCase) EXPECT() *MockCobaDuaUseCaseMockRecorder {
	return m.recorder
}

// CreateCobaDua mocks base method.
func (m *MockCobaDuaUseCase) CreateCobaDua(ctx context.Context, dto usecase.DTOCobaDua) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCobaDua", ctx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCobaDua indicates an expected call of CreateCobaDua.
func (mr *MockCobaDuaUseCaseMockRecorder) CreateCobaDua(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCobaDua", reflect.TypeOf((*MockCobaDuaUseCase)(nil).CreateCobaDua), ctx, dto)
}

// DeleteCobaDua mocks base method.
func (m *MockCobaDuaUseCase) DeleteCobaDua(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCobaDua", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCobaDua indicates an expected call of DeleteCobaDua.
func (mr *MockCobaDuaUseCaseMockRecorder) DeleteCobaDua(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCobaDua", reflect.TypeOf((*MockCobaDuaUseCase)(nil).DeleteCobaDua), ctx, id)
}

// GetCobaDuaByID mocks base method.
func (m *MockCobaDuaUseCase) GetCobaDuaByID(ctx context.Context, id string) (*entity.CobaDua, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCobaDuaByID", ctx, id)
	ret0, _ := ret[0].(*entity.CobaDua)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCobaDuaByID indicates an expected call of GetCobaDuaByID.
func (mr *MockCobaDuaUseCaseMockRecorder) GetCobaDuaByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCobaDuaByID", reflect.TypeOf((*MockCobaDuaUseCase)(nil).GetCobaDuaByID), ctx, id)
}

// GetListCobaDua mocks base method.
func (m *MockCobaDuaUseCase) GetListCobaDua(ctx context.Context, request *goutils.RequestOption) ([]*entity.CobaDua, *goutils.MetaResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListCobaDua", ctx, request)
	ret0, _ := ret[0].([]*entity.CobaDua)
	ret1, _ := ret[1].(*goutils.MetaResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetListCobaDua indicates an expected call of GetListCobaDua.
func (mr *MockCobaDuaUseCaseMockRecorder) GetListCobaDua(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListCobaDua", reflect.TypeOf((*MockCobaDuaUseCase)(nil).GetListCobaDua), ctx, request)
}

// UpdateCobaDua mocks base method.
func (m *MockCobaDuaUseCase) UpdateCobaDua(ctx context.Context, id string, dto usecase.DTOCobaDua) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCobaDua", ctx, id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCobaDua indicates an expected call of UpdateCobaDua.
func (mr *MockCobaDuaUseCaseMockRecorder) UpdateCobaDua(ctx, id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCobaDua", reflect.TypeOf((*MockCobaDuaUseCase)(nil).UpdateCobaDua), ctx, id, dto)
}
